// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dev_tuningfork.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Android.PerformanceTuner {

  /// <summary>Holder for reflection information generated from dev_tuningfork.proto</summary>
  public static partial class DevTuningforkReflection {

    #region Descriptor
    /// <summary>File descriptor for dev_tuningfork.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DevTuningforkReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRkZXZfdHVuaW5nZm9yay5wcm90byJuCgpBbm5vdGF0aW9uEiQKDWxvYWRp",
            "bmdfc3RhdGUYASABKA4yDS5Mb2FkaW5nU3RhdGUSFQoFc2NlbmUYAiABKA4y",
            "Bi5TY2VuZRIjCg5nYW1lZGlmZmljdWx0eRgDIAEoDjILLkRpZmZpY3VsdHki",
            "cAoORmlkZWxpdHlQYXJhbXMSGgoSdGV4dHVyZV9yZXNvbHV0aW9uGAEgASgF",
            "EigKD3NoYWRvd19xdWFsdGl0eRgCIAEoDjIPLlNoYWRvd1F1YWx0aXR5EhgK",
            "EHBhcnRpY2xlX2RldGFpbHMYAyABKAIqYAoMTG9hZGluZ1N0YXRlEhgKFExP",
            "QURJTkdTVEFURV9JTlZBTElEEAASHAoYTE9BRElOR1NUQVRFX05PVF9MT0FE",
            "SU5HEAESGAoUTE9BRElOR1NUQVRFX0xPQURJTkcQAirsAQoFU2NlbmUSEQoN",
            "U0NFTkVfSU5WQUxJRBAAEjMKL1NDRU5FX0FTU0VUU19HQU1FQVNTRVRTV09S",
            "RFBVWlpMRV9TQ0VORVNMT0FESU5HEAESMAosU0NFTkVfQVNTRVRTX0dBTUVB",
            "U1NFVFNXT1JEUFVaWkxFX1NDRU5FU0hPTUUQAhI3CjNTQ0VORV9BU1NFVFNf",
            "R0FNRUFTU0VUU1dPUkRQVVpaTEVfU0NFTkVTU0VMRUNUV09STEQQAxIwCixT",
            "Q0VORV9BU1NFVFNfR0FNRUFTU0VUU1dPUkRQVVpaTEVfU0NFTkVTTUFJThAE",
            "KmUKCkRpZmZpY3VsdHkSFgoSRElGRklDVUxUWV9JTlZBTElEEAASEwoPRElG",
            "RklDVUxUWV9FQVNZEAESFQoRRElGRklDVUxUWV9NRURJVU0QAhITCg9ESUZG",
            "SUNVTFRZX0hBUkQQAyp4Cg5TaGFkb3dRdWFsdGl0eRIaChZTSEFET1dRVUFM",
            "VElUWV9JTlZBTElEEAASFgoSU0hBRE9XUVVBTFRJVFlfTE9XEAESGQoVU0hB",
            "RE9XUVVBTFRJVFlfTUVESVVNEAISFwoTU0hBRE9XUVVBTFRJVFlfSElHSBAD",
            "QiKqAh9Hb29nbGUuQW5kcm9pZC5QZXJmb3JtYW5jZVR1bmVyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Android.PerformanceTuner.LoadingState), typeof(global::Google.Android.PerformanceTuner.Scene), typeof(global::Google.Android.PerformanceTuner.Difficulty), typeof(global::Google.Android.PerformanceTuner.ShadowQualtity), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Android.PerformanceTuner.Annotation), global::Google.Android.PerformanceTuner.Annotation.Parser, new[]{ "LoadingState", "Scene", "Gamedifficulty" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Android.PerformanceTuner.FidelityParams), global::Google.Android.PerformanceTuner.FidelityParams.Parser, new[]{ "TextureResolution", "ShadowQualtity", "ParticleDetails" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum LoadingState {
    [pbr::OriginalName("LOADINGSTATE_INVALID")] Invalid = 0,
    [pbr::OriginalName("LOADINGSTATE_NOT_LOADING")] NotLoading = 1,
    [pbr::OriginalName("LOADINGSTATE_LOADING")] Loading = 2,
  }

  public enum Scene {
    [pbr::OriginalName("SCENE_INVALID")] Invalid = 0,
    [pbr::OriginalName("SCENE_ASSETS_GAMEASSETSWORDPUZZLE_SCENESLOADING")] AssetsGameassetswordpuzzleScenesloading = 1,
    [pbr::OriginalName("SCENE_ASSETS_GAMEASSETSWORDPUZZLE_SCENESHOME")] AssetsGameassetswordpuzzleSceneshome = 2,
    [pbr::OriginalName("SCENE_ASSETS_GAMEASSETSWORDPUZZLE_SCENESSELECTWORLD")] AssetsGameassetswordpuzzleScenesselectworld = 3,
    [pbr::OriginalName("SCENE_ASSETS_GAMEASSETSWORDPUZZLE_SCENESMAIN")] AssetsGameassetswordpuzzleScenesmain = 4,
  }

  public enum Difficulty {
    [pbr::OriginalName("DIFFICULTY_INVALID")] Invalid = 0,
    [pbr::OriginalName("DIFFICULTY_EASY")] Easy = 1,
    [pbr::OriginalName("DIFFICULTY_MEDIUM")] Medium = 2,
    [pbr::OriginalName("DIFFICULTY_HARD")] Hard = 3,
  }

  public enum ShadowQualtity {
    [pbr::OriginalName("SHADOWQUALTITY_INVALID")] Invalid = 0,
    [pbr::OriginalName("SHADOWQUALTITY_LOW")] Low = 1,
    [pbr::OriginalName("SHADOWQUALTITY_MEDIUM")] Medium = 2,
    [pbr::OriginalName("SHADOWQUALTITY_HIGH")] High = 3,
  }

  #endregion

  #region Messages
  public sealed partial class Annotation : pb::IMessage<Annotation> {
    private static readonly pb::MessageParser<Annotation> _parser = new pb::MessageParser<Annotation>(() => new Annotation());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Annotation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Android.PerformanceTuner.DevTuningforkReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Annotation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Annotation(Annotation other) : this() {
      loadingState_ = other.loadingState_;
      scene_ = other.scene_;
      gamedifficulty_ = other.gamedifficulty_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Annotation Clone() {
      return new Annotation(this);
    }

    /// <summary>Field number for the "loading_state" field.</summary>
    public const int LoadingStateFieldNumber = 1;
    private global::Google.Android.PerformanceTuner.LoadingState loadingState_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Android.PerformanceTuner.LoadingState LoadingState {
      get { return loadingState_; }
      set {
        loadingState_ = value;
      }
    }

    /// <summary>Field number for the "scene" field.</summary>
    public const int SceneFieldNumber = 2;
    private global::Google.Android.PerformanceTuner.Scene scene_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Android.PerformanceTuner.Scene Scene {
      get { return scene_; }
      set {
        scene_ = value;
      }
    }

    /// <summary>Field number for the "gamedifficulty" field.</summary>
    public const int GamedifficultyFieldNumber = 3;
    private global::Google.Android.PerformanceTuner.Difficulty gamedifficulty_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Android.PerformanceTuner.Difficulty Gamedifficulty {
      get { return gamedifficulty_; }
      set {
        gamedifficulty_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Annotation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Annotation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoadingState != other.LoadingState) return false;
      if (Scene != other.Scene) return false;
      if (Gamedifficulty != other.Gamedifficulty) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoadingState != 0) hash ^= LoadingState.GetHashCode();
      if (Scene != 0) hash ^= Scene.GetHashCode();
      if (Gamedifficulty != 0) hash ^= Gamedifficulty.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoadingState != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) LoadingState);
      }
      if (Scene != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Scene);
      }
      if (Gamedifficulty != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Gamedifficulty);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoadingState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LoadingState);
      }
      if (Scene != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Scene);
      }
      if (Gamedifficulty != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gamedifficulty);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Annotation other) {
      if (other == null) {
        return;
      }
      if (other.LoadingState != 0) {
        LoadingState = other.LoadingState;
      }
      if (other.Scene != 0) {
        Scene = other.Scene;
      }
      if (other.Gamedifficulty != 0) {
        Gamedifficulty = other.Gamedifficulty;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            loadingState_ = (global::Google.Android.PerformanceTuner.LoadingState) input.ReadEnum();
            break;
          }
          case 16: {
            scene_ = (global::Google.Android.PerformanceTuner.Scene) input.ReadEnum();
            break;
          }
          case 24: {
            gamedifficulty_ = (global::Google.Android.PerformanceTuner.Difficulty) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class FidelityParams : pb::IMessage<FidelityParams> {
    private static readonly pb::MessageParser<FidelityParams> _parser = new pb::MessageParser<FidelityParams>(() => new FidelityParams());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FidelityParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Android.PerformanceTuner.DevTuningforkReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FidelityParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FidelityParams(FidelityParams other) : this() {
      textureResolution_ = other.textureResolution_;
      shadowQualtity_ = other.shadowQualtity_;
      particleDetails_ = other.particleDetails_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FidelityParams Clone() {
      return new FidelityParams(this);
    }

    /// <summary>Field number for the "texture_resolution" field.</summary>
    public const int TextureResolutionFieldNumber = 1;
    private int textureResolution_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TextureResolution {
      get { return textureResolution_; }
      set {
        textureResolution_ = value;
      }
    }

    /// <summary>Field number for the "shadow_qualtity" field.</summary>
    public const int ShadowQualtityFieldNumber = 2;
    private global::Google.Android.PerformanceTuner.ShadowQualtity shadowQualtity_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Android.PerformanceTuner.ShadowQualtity ShadowQualtity {
      get { return shadowQualtity_; }
      set {
        shadowQualtity_ = value;
      }
    }

    /// <summary>Field number for the "particle_details" field.</summary>
    public const int ParticleDetailsFieldNumber = 3;
    private float particleDetails_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float ParticleDetails {
      get { return particleDetails_; }
      set {
        particleDetails_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FidelityParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FidelityParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TextureResolution != other.TextureResolution) return false;
      if (ShadowQualtity != other.ShadowQualtity) return false;
      if (ParticleDetails != other.ParticleDetails) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TextureResolution != 0) hash ^= TextureResolution.GetHashCode();
      if (ShadowQualtity != 0) hash ^= ShadowQualtity.GetHashCode();
      if (ParticleDetails != 0F) hash ^= ParticleDetails.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TextureResolution != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TextureResolution);
      }
      if (ShadowQualtity != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ShadowQualtity);
      }
      if (ParticleDetails != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(ParticleDetails);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TextureResolution != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TextureResolution);
      }
      if (ShadowQualtity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ShadowQualtity);
      }
      if (ParticleDetails != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FidelityParams other) {
      if (other == null) {
        return;
      }
      if (other.TextureResolution != 0) {
        TextureResolution = other.TextureResolution;
      }
      if (other.ShadowQualtity != 0) {
        ShadowQualtity = other.ShadowQualtity;
      }
      if (other.ParticleDetails != 0F) {
        ParticleDetails = other.ParticleDetails;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TextureResolution = input.ReadInt32();
            break;
          }
          case 16: {
            shadowQualtity_ = (global::Google.Android.PerformanceTuner.ShadowQualtity) input.ReadEnum();
            break;
          }
          case 29: {
            ParticleDetails = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
